# Generated by Django 5.1.1 on 2024-09-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_dis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
